### ISSUE TITLE
Expose INSTALL_K3S_CHANNEL related configuration

### ISSUE THREAD

**Issue by consideRatio** [manics/action-k3s-helm#5]
We can support specification of `INSTALL_K3S_CHANNEL`, a functionality that didn't exist before. It allow us to not specify a specific k3s version but instead a release channel defined in https://update.k3s.io/v1-release/channels such as:

- v1.16
- v1.17
- v1.18
- v1.19
- stable (not sure if this will be different from latest in general)
- latest

I learned about this about re-inspecting the https://get.k3s.io/ script hat I now found to support it.

**Comment by manics** [comment]
Thanks for point this out. I'm undecided on whether the additional logic is worth it. In most of my own projects I've moved towards using exact dependencies for testing and relying on dependabot to bump versions, which greatly reduces the time spent debugging CI failures- if you haven't pinned an exact version you're always left thinking is this a flakey test, is it a one-off failure, is there a bug in an unpinned dependency, or is it a genuine failure. Obviously dependabot doesn't support bumping versions for  GitHub releases, so it updating k3s would require a manual bump. A custom GitHub action to bump versions could be another option.

Are you planning to always use `1.X` instead of `1.X.Y` in all CI, or are you mentioning this to start a discussion?

**Comment by consideRatio** [comment]
> In most of my own projects I've moved towards using exact dependencies for testing and relying on dependabot to bump versions, which greatly reduces the time spent debugging CI failures- if you haven't pinned an exact version you're always left thinking is this a flakey test, is it a one-off failure, is there a bug in an unpinned dependency, or is it a genuine failure.

Yeah I think this may be the best practice, but sometimes, for example with `helm`, I'd prefer to keep updated using the latest version to avoid getting outdated and catch things as they are causing problems quick.

I planned to use it in a private repo for example, but is it wise to do so? Maybe not. I suggest we don't take any action but keep it as a thought that it could be nice to enable this somehow if planning to enable something general.

For example, a passthrough mechanism to set k3s flags? A passthrought mechanism to set environment variables to influence the k3s script (this is probably solved by using `env` of the action though, which could be a documented example) for this repo.

**Comment by consideRatio** [comment]
Closing this for now, I think the action point to potentially do at some point would be to document how to do various things one may want and avoid introducing custom stuff in this action that is hard to maintain and such.
